/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posttest6;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS.DX
 */
public class posttest6 extends javax.swing.JFrame {
private DefaultTableModel model;
private final Connection con = koneksi.getConnection();
private Statement stt;
private ResultSet rss;
private PreparedStatement pst;
int id;
    /**
     * Creates new form posttest6
     */
    public posttest6() {
        initComponents();
    }
private void InitTable(){//inisiasi tabel atau membuat table secara manual
        model = new DefaultTableModel(); //instansi class model dari class defaulttablemodel
        model.addColumn("JUDUL"); //membuat kolom judul di instans class model
        model.addColumn("PENULIS"); //membuat kolom penulis di instans class model
        model.addColumn("HARGA"); // membuat kolom harga di instance class model
        model.addColumn("ID"); //Menambah kolom dengan nama ID
        jTable1.setModel(model);
        jTable1.getColumn("ID").setPreferredWidth(0);
        jTable1.getColumn("ID").setMinWidth(0);
        jTable1.getColumn("ID").setWidth(0);
        jTable1.getColumn("ID").setMaxWidth(0); //Pada getColumn("ID") bertujuan untuk mengecilkan agar tidak tampak kolom ID tersebut
        //Kolom id digunakan untuk mengubah dan menghapus
       
    
    }

   private boolean validasi(String judul){ //mthod agar tidk ada data yang sama ketika dibuat
       try{ //untuk membuat eksepsi
           stt = con.createStatement(); //agar konek db
           String sql = "SELECT * FROM buku where judul='"+judul+"'"; //mendeklarasikan variabel sql dengan query untuk menampilkan data sesuai kondisi judul yang ditentukan
           rss = stt.executeQuery(sql); //untuk konek ke db
           if(rss.next())
               return true;
           else
               return false;
       }catch(SQLException e){ //menangkap sebuah error pada SQL
           System.out.println(e.getMessage());
           return false;
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        pilih = new javax.swing.JComboBox();
        penulis = new javax.swing.JComboBox();
        Tjudul = new javax.swing.JTextField();
        Tharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        idd = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BTsimpan = new javax.swing.JButton();
        BTubah = new javax.swing.JButton();
        BThapus = new javax.swing.JButton();
        BTkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("SF Sports Night Upright", 0, 24)); // NOI18N
        jLabel6.setText("Form Data Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel6)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Judul ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Penulis");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Search");

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cariKeyTyped(evt);
            }
        });

        pilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Judul", "Penulis", "Harga" }));

        penulis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kadoya tsukatsa", "masahiro inoue", "tomari shinosuke", "hojo emu", "dan kuroto" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul", "Penulis", "Harga", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        BTsimpan.setText("Simpan");
        BTsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsimpanActionPerformed(evt);
            }
        });
        jPanel3.add(BTsimpan);

        BTubah.setText("Ubah");
        BTubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTubahActionPerformed(evt);
            }
        });
        jPanel3.add(BTubah);

        BThapus.setText("Hapus");
        BThapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThapusActionPerformed(evt);
            }
        });
        jPanel3.add(BThapus);

        BTkeluar.setText("Keluar");
        BTkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTkeluarActionPerformed(evt);
            }
        });
        jPanel3.add(BTkeluar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Tjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(penulis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(444, 444, 444)
                                .addComponent(idd))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(penulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Tharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idd))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BTkeluarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        InitTable();
        TampilData();
    }//GEN-LAST:event_formComponentShown

    private void BTsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsimpanActionPerformed
        // TODO add your handling code here:
        TambahData();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        TampilData();
        Tjudul.setText("");
        Tharga.setText("");
//        idd.setText("");
    }//GEN-LAST:event_BTsimpanActionPerformed

    private void BTubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTubahActionPerformed
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        UpdateData();
        TampilData();
        Tjudul.setText("");
        Tharga.setText("");
    }//GEN-LAST:event_BTubahActionPerformed

    private void BThapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThapusActionPerformed
        // TODO add your handling code here:
        HapusData();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        TampilData();
        Tjudul.setText("");
        Tharga.setText("");
        BTubah.setEnabled(false);
        BThapus.setEnabled(false);
    }//GEN-LAST:event_BThapusActionPerformed

    private void cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyTyped
        // TODO add your handling code here:
           model.getDataVector().removeAllElements();//mendeklarasikan model yang mmengambil data vector dan meremove semua ellements
       model.fireTableDataChanged();//mendeklarasikan model yang di fireTableDataChanged
       String caridengan = pilih.getSelectedItem().toString();
       try{
           String sql = "select * from buku where "+caridengan+" like '%"+cari.getText()+"%'";
           stt = con.createStatement();//pembuatan statement
           rss = stt.executeQuery(sql);//eksekusi query
           ResultSet rss=stt.executeQuery(sql);
           while(rss.next()){// perulangan result set dari variable rss hingga tidak terpenuhi untuk perulangan
                //menampilkan data sesuai array :
               Object[] o=new Object[3];
               o[0]=rss.getString("JUDUL");
               o[1]=rss.getString("PENULIS");
               o[2]=rss.getString("HARGA");
               model.addRow(o);
           }
           stt.close();//menutup stt
           rss.close();//menutup rss
       }catch(SQLException e){System.out.println("Terjadi Kesalahan");}
    }//GEN-LAST:event_cariKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        String judull=jTable1.getValueAt(baris, 0).toString();
        String penuliss=jTable1.getValueAt(baris, 1).toString();
        String hargaa=jTable1.getValueAt(baris, 2).toString();
        String ids = jTable1.getValueAt(baris, 3).toString();
        
        idd.setText(ids);
        Tjudul.setText(judull);
        penulis.setSelectedItem(penuliss);
        Tharga.setText(hargaa);   
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //Event yang berfungsi jika jTable di klik
        BTubah.setEnabled(true);
        BThapus.setEnabled(true);
        int baris = jTable1.getSelectedRow();
        String judull=jTable1.getValueAt(baris, 0).toString();
        String penuliss=jTable1.getValueAt(baris, 1).toString();
        String hargaa=jTable1.getValueAt(baris, 2).toString();
        String ids = jTable1.getValueAt(baris, 3).toString();
        
        idd.setText(ids);
        Tjudul.setText(judull);
        penulis.setSelectedItem(penuliss);
        Tharga.setText(hargaa);
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        BTubah.setEnabled(false);
        BThapus.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(posttest6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(posttest6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(posttest6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(posttest6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new posttest6().setVisible(true);
            }
        });
    }

     private void TampilData(){ //Merupakan fungsi yang Bernama TampilData yang digunakan untuk menampilkan data dari Databases tabel buku
        try{
            String sql = "SELECT * FROM buku"; //Fungsi sql yang berfungsi untuk menampilkan data dari tabel buku
            stt = con.createStatement();
            rss = stt.executeQuery(sql); //Yang menjalankan fungsi sql yang telah ditulis
            while(rss.next()){ // perulangan result set dari variable rss hingga tidak terpenuhi untuk perulangan
                //menampilkan data sesuai array :
                Object[] o = new Object[4];
                o[0] = rss.getString("judul"); //Data kolom judul dari tabel buku dimasukkan kedalam object o
                o[1] = rss.getString("penulis"); //Data kolom penulis dari tabel buku dimasukkan kedalam object o
                o[2] = rss.getInt("harga"); //Data kolom harga dari tabel buku dimasukkan kedalam object o
                o[3] = rss.getInt("id"); //Data kolom id dari tabel buku dimasukkan kedalam object o
                model.addRow(o); // Data-data tadi lalu di masukkan kedalam jTable1
                
            }
        }catch(SQLException e){
            System.out.println(e.getMessage()); //Menangkap kesalahan jika misalnya terjadi
        }
        
    }
    private void TambahData(){ //Fungsi yang berfungsi untuk menambah data ke databases tabel buku
        String judull = Tjudul.getText();
        String penuliss = penulis.getSelectedItem().toString();
        int hargaa = Integer.parseInt(Tharga.getText());
        try{
            String sql = "INSERT INTO buku VALUES(NULL,'"+judull+"','"+penuliss+"',"+hargaa+")"; 
            //Fungsi SQL yang digunakan untuk memasukan data yaitu Insert
            stt = con.createStatement();
            stt.executeUpdate(sql); //executeUpdate adalah yang menjalankan querynya
            model.addRow(new Object[]{judull,penuliss,hargaa});
        }catch(SQLException e){
            System.out.println(e.getMessage()); //Menangkap kesalahan jika terjadi
        }
    }
    
    private void HapusData(){ //Fungsi yang digunakkan untuk menghapus data dari tabel buku di databases
        String judull = Tjudul.getText();
        String penuliss = penulis.getSelectedItem().toString();
        int hargaa= Integer.parseInt(Tharga.getText());
        int ids = Integer.parseInt(idd.getText()); //Mengambil data ID yang dari jLabel idd
        try{
            String sql = "delete from buku where id='"+ids+"'";
            //Menghapus data dengan id = ids, ids berisi id penulis dan lain-lain
            stt = con.createStatement();
            stt.executeUpdate(sql); //  yang menjalankan query sql
        }catch(SQLException e){
            System.out.println(e.getMessage()); //Menangkap kesalahan jika terjadi
        }
    }
   private void UpdateData(){ //Fungsi yang digunakkan untuk mengubah data atau mengupdate data
//        int baris = jTable1.getSelectedRow();
        String judull = Tjudul.getText(); //Mengambil judul yang dari jTextfield txtJudul
        String penuliss = penulis.getSelectedItem().toString();  //Mengambil penulis yang dari comboPenulis
        int hargaa = Integer.parseInt(Tharga.getText()); //Mengambil data harga yang dari jTextfield txtHarga
        int ids = Integer.parseInt(idd.getText()); //Mengambil data ID yang dari jLabel idd
        try
        {
            String sql = "update buku set judul='"+judull+"', penulis='"+penuliss+"', harga='"+hargaa+"'Where id='"+ids+"'";
            //query sql untuk mengupdate dimana id = ids, ids berisi id penulis dan lain-lain
            stt = con.createStatement();
            stt.executeUpdate(sql); // yang menjalankan querynya
        }catch(SQLException e){
            System.out.println(e.getMessage()); //Menangkap kesalahan jika terjadi
        }
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BThapus;
    private javax.swing.JButton BTkeluar;
    private javax.swing.JButton BTsimpan;
    private javax.swing.JButton BTubah;
    private javax.swing.JTextField Tharga;
    private javax.swing.JTextField Tjudul;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel idd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox penulis;
    private javax.swing.JComboBox pilih;
    // End of variables declaration//GEN-END:variables
}
